<div class="header--top__left">
    <?=
        $this->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('header-top-left')
        ->toHtml();
    ?>
</div>

<div class="header--top__middle">
    <?=
        $this->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('header-top-middle')
        ->toHtml();
    ?>
</div>

<div class="header--top__right">
    <?=
        $this->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('header-top-right')
        ->toHtml();
    ?>
</div>