<div>
    <?= $this->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer-middle-categories')
        ->toHtml();
    ?>
</div>
<div>
    <?= $this->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer-middle-why-burning-log')
        ->toHtml();
    ?>
</div>
<div>
    <?= $this->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer-middle-policies')
        ->toHtml();
    ?>
</div>