<div class="footer-containner">
    <div>
        <?= $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('footer-showroom-left')
            ->toHtml();
        ?>
    </div>
    <div>
        <?= $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('footer-showroom-center')
            ->toHtml();
        ?>
    </div>
    <div>
        <?= $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('footer-showroom-right')
            ->toHtml();
        ?>
    </div>
</div>